rstudio/shiny-server

- packaging/make-package.sh
becuase they hide errors when using certain versions of bash.
> Avoid subshells like the plague

- packaging/make-package.sh
also be explicit where possible about node
Keeps package building in-sync with our wiki build instructions, which were updated per #108.
> our bin must be first to triumph over system-installed node

- NEWS
- package.json
Bump version and update NEWS for 1.4.0. Here are the differences from the 1.3.0 tag:
https://github.com/rstudio/shiny-server/compare/v1.3.0...master
After this is finalized, we still need to apply the v1.4.0 tag.
> v1.4.0 version bump

- config/systemd/shiny-server.debian.service
- packaging/debian-control/postinst.in
- packaging/debian-control/prerm.in
- vagrant/ubuntu15.04/.gitignore
- vagrant/ubuntu15.04/Vagrantfile
- vagrant/ubuntu15.04/setup.sh
The systemd script could probably be a lot simpler; we shouldn't
need a PIDFILE if we're not running in daemon mode. And I have a
feeling we shouldn't be writing into /var/log/shiny-server.log for
the main server, but rather to the systemd journal.
However, in the interest of getting a working build out to 15.04
users ASAP, and not having to retest Red Hat 7, we'll just take
our existing systemd file with minimal changes.
> Add systemd script for Ubuntu 15.04

- packaging/rpm-script/postinst.sh.in
By keeping the files that yum installs present, we make yum happier when
it goes to uninstall those files. So we'll copy instead of mv as a quick
fix.
Eventually, the right answer is actually to move this intelligence to
CMake and only ship with the appropriate version of pandoc. I had spent
a few hours on it many months ago and ended up deciding this was better
than wasting a day on it.
> Copy instead of move Pandoc

- latest/index.html
This section explains setting .Rprofile or Rprofile.site files, but the code:
```R
local({
r <- getOptions("repos")
r["CRAN"] <- "https://cran.rstudio.com/"
options(repos=r)
})
```
causes errors when trying to install a package as `getOptions` isn't a function, `getOption` is correct (I think)
```R
local({
r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com/"
options(repos=r)
})
```
> Install shiny section

- lib/worker/app-worker.js
On (at least) RHEL7, su's -p switch is clobbered by the --login switch, meaning that the current directory is no longer maintained across the su call. Instead, the user's home directory will be the dir of the executed command. For us, that means the app is running out of the wrong directory and will not properly respect things like an .RProfile in the app dir.
Fixes #143
@fereshtehRS it will be worthwhile to test this across distros. I haven't seen any problems with this syntax where I've tested, but it is a deviation in syntax from how we've spawned R in the past.
> Explicitly cd into the appropriate directory.

- CMakeLists.txt
- R/SockJSAdapter.R
- config/shiny-server-rules.config
- lib/router/config-router.js
- lib/router/directory-router.js
- lib/router/router.js
- lib/router/user-dirs-router.js
- lib/scheduler/scheduler.js
- lib/worker/app-spec.js
- lib/worker/app-worker.js
- scripts/mkdir.sh
- vagrant/nfs/README.md
- vagrant/nfs/Vagrantfile
- vagrant/nfs/bootstrap-debian.sh
- vagrant/nfs/provision-nfs.sh
- vagrant/nfs/provision-sso.sh
- vagrant/nfs/shiny-server.conf
I think we're at a stopping point, albeit a disappointing one.
This PR adds a config option which removes the requirement for root to have write access for `~/ShinyApps/log` when spawning R processes on behalf of another user. This requirements presents problems for e.g. `root_squash`'d NFS mounts.
Unfortunately, there's still quite a bit of complicated code that requires read access to the user's ShinyApps dir so that we can find where the application is that we're supposed to be hosting and what mode we should be in. This is going to be complicated to replace with code that runs as another user.
The ultimate approach to fixing this may be to write a wrapper around the `fs` module that does at least some of that functionality with `uid` and `gid` parameters, which replicates the native …
> Don't require root write access to log directories.

- lib/worker/app-worker.js
- Fixes bug in which log directory wouldn't be created in non-log_as_user mode
- Doesn't presume user_dirs log locations when using log_as_user.
> Ensure logdir var exists.

- R/SockJSAdapter.R
- assets/shiny-server.css
- assets/shiny-server.js
- config/shiny-server-rules.config
- lib/main.js
- lib/proxy/multiplex.js
- lib/proxy/robust-sockjs.js
- lib/proxy/sockjs.js
- lib/router/config-router.js
- test/robust-sockjs.js
Behavior:
- If `disable_reconnect true` is set in the config, then the behavior mimics what we have today, with the subtle exception that Shiny Server, instead of Shiny, is producing the grey screen on disconnect (with slightly different mechanics). By default, the feature is enabled, though.
- If we have an unexpected disconnect, we'll present they grey screen with a dialog at the top counting down from 15 seconds. The R session will stay active for this same amount of time. If the user clicks "reconnect" within those 15 seconds, they'll be reattached to their original session with no lost state.
- After 15 seconds with no user intervention, we'll close the connection to the Shiny process, and the UI will no longer offer to "reconnect" but rather will say that you've been disconnected …
> Add reconnect capabilities

- assets/shiny-server.js
Silently tries to reconnect in the background for 3.5s, then shows the reconnecting screen with countdowns until the next reconnect attempt.
Out of scope for this PR:
- UI improvements
- "connect now" link
> Enable auto-reconnect

- assets/shiny-server.js
I think we were over-communicating with the to-the-second countdown on reconnects. I'm modeling this after Pivotal Tracker's disconnect dialog which is much simpler. It just says "Disconnected from server" with a reconnect now button, but also periodically tries to reconnect. I'm guessing that may be what we want: give the user the option to fix it immediately, otherwise do our best in the background.
(CC @wch)
> Add a reconnect now button, eliminate countdown.

- lib/main.js
no-cache is sufficient to discourage browsers from serving the
cached version of a file. With browser history and/or tab
reopening, however, the browser /will/ use the cached version of the
file (tested on Chrome and Firefox). Thus, if a file is essential in
order to reload the state of a tab (as is the case for the templated
shiny-server.js), you need to allow the browser to store so that it
will have a copy of shiny-server.js when it re-opens the tab.
This commit restores the "disconnect" dialog box when reopening a closed
tab while offline.
> Don't forbid storage of templated files.

- lib/main.js
- lib/proxy/sockjs.js
If reconnects are disabled, don't even use the RobustSockJS server.
Send the connection directly to the multiplexer like we used to so that
the robustification feature is completely disabled.
> Don't proxy connections through robustification

- packaging/debian-control/postinst.in
- packaging/debian-control/prerm.in
Debian package didn't install /etc/init/shiny-server.conf due to failed test for system id. A test for system id of "LinuxMint" should fix this. I checked the test statements, but did not test the installer.
> Use upstart for server management under Mint Linux

- R/SockJSAdapter.R
- config/shiny-server-rules.config
- lib/proxy/http.js
- lib/proxy/sockjs.js
- lib/router/config-router-util.js
- lib/worker/app-worker.js
- node_modules/sockjs/node_modules/.bin/uuid
- vagrant/ubuntu14.04/Vagrantfile
There's an [outstanding shiny PR](https://github.com/rstudio/shiny/pull/1156) right now that adds a shiny option to sanitize the errors that appear in the UI/app itself (the default is sanitized errors: `options(shiny.sanitize.errors = TRUE)`). This leaves the console logs unchanged but now to see these, you need to either have access to the console (like in local development) or to the console logs stored in shiny server. This decreases security risks -- no chance of some sensitive information leaking through to the end user via an error message. 
This PR enables the system admins for shiny server to set `shiny.sanitize.errors` according to their needs. The default is sanitized errors, but if people are not worried about security, they can override this by adding `sanitize_errors false` …
> Enabling error hiding option through config file

- lib/router/config-router-util.js
Fixes #229.
Updated the config-router-util to work correctly when the 'disable_websockets true;' is set in the shiny-server.conf.
The current implementation throws this error:
```[ERROR] shiny-server - Error loading config: Cannot call method 'push' of undefined```
> Updated the config-router-util to work with 'disable_websockets true;'

- R/SockJSAdapter.R
Previously the path used for bookmarking was not separated per app. For example, it would put files in:
```
/var/lib/shiny-server/bookmarks/shiny/76460940f1cd9dfb
```
Instead of the intended destination:
```
/var/lib/shiny-server/bookmarks/shiny/myApp-6fbdbedc4c99d052b538b2bfc3c96550/76460940f1cd9dfb
```
This pull request corrects that.
> Use correct bookmarking directory

- R/SockJSAdapter.R
- lib/worker/app-worker.js
Previously, each application would have its bookmark state directory created on startup, even if it wasn't needed. Now the application's bookmark directory is created only when bookmarking is actually attempted.
This PR also fixes a bug where it attempted to restore bookmarks from the wrong directory. Not sure how I missed that in testing before. :(
> Create application's bookmark state directory only when needed

- NEWS
- lib/proxy/robust-sockjs.js
- test/robust-sockjs.js
(This is a change that was in shiny-server-pro since January.)
When a reconnection occurs, there's no need in lib/proxy/sockjs.js
to call onMultiplexConnect; that logic has already been called on
the robustConn object, the first time it was returned from robustify.
It turns out that most times this doesn't make a difference, maybe
because it's unlikely after a reconnect for another multiplex
channel to connect itself (i.e. a new subapp appears); most Shiny
apps either don't have subapps, or only load subapps during startup.
Otherwise I think it's likely we would have seen handleMultiplexChannel
called multiple times on a single channel.
Here's a sample app that will demonstrate the bad behavior. Start
shiny-server with SHINY_LOG_LEVEL=TRACE; load the app in a browser;
in the JS console, …
> Don't return reused connection from robustify()

- npm-shrinkwrap.json
- package.json
This upgrade fixes a regression where the protocol chooser UI
shows all protocols, regardless of whether the server has them
enabled or not.
Older versions of SS/SSP hide the protocols that are disabled.
Versions that used prior versions of shiny-server-client show
all the protocols. This change still shows all the protocols,
but now greys out the ones that are not enabled by the server.
> Upgrade shiny-server-client

- lib/main.js
- npm-shrinkwrap.json
- package.json
Fixes the crashing error when access_log directive is used.
> Replace (missing) express logger with morgan

- lib/proxy/http.js
- test/proxy-events.js
Bitten again by node-http-proxy event changes :( When an ECONNRESET
occurs between the proxy and the target (Shiny process), we were
expecting to see that error come in on the "error" event (and in
earlier versions it was "proxyError"). But earlier this year, this
specific error code was pulled out of the "error" event and raised
as a unique "econnreset" event, without the docs being updated.
Also added a test so the build will fail if we upgrade http-proxy
and it adds new events.
> Fix #506: R process not terminating in certain scenario

- NEWS
- lib/proxy/robust-sockjs.js
- package.json
(cc @trestletech @jonyoder @fereshtehRS)
This is a serious connectivity regression that was introduced with RobustSockJS (unclear whether it was the shiny-server-client version or the earlier one that introduced it). We should consider this for immediate patch of 1.5.0.
---
Before this fix, some proxy configurations were working for Shiny
Server 1.4.3 but not in 1.5.0. (I can't vouch for the state of
versions in between.)
Basically, with 1.4.3 SockJS was able to fall gracefully back from
websockets, to xhr-streaming, to xhr-polling. With 1.5.0, SockJS
does all this but when it finally finds a transport that works,
Shiny Server kills the connection, and in the server log there's a
message about RobustSockJS collision.
I believe this is because the proxy is letting the request through …
> Fix SockJS transport fallback

- NEWS
- config/shiny-server-rules.config
- lib/main.js
- lib/proxy/sockjs.js
- lib/router/config-router.js
A user reported disconnects when users on **slow internet connections** try to use apps that have **large outputs** (it's unrelated to how long the outputs take to calculate, it's purely the payload size that matters).
I was able to repro using the following app, plus using commands to slow down the network interface on Linux:
```r
library(shiny)
ui <- fluidPage(
"Hello",
plotOutput("plot")
)
server <- function(input, output, session) {
session$sendCustomMessage("test", 1:3E6)
output$plot <- renderPlot(plot(cars))
}
shinyApp(ui, server)
```
This app sends a ~22MB payload to the client (which is ignored) before rendering the plot.
Run this command on the server to slow down one of the network interfaces (tested on Ubuntu):
```bash
sudo tc qdisc add dev <network-interface> root netem delay …
```
> More control over http keepalive and sockjs timeouts

- NEWS
- lib/core/url-util.js
- lib/proxy/http.js
- lib/proxy/sockjs.js
- lib/scheduler/scheduler-registry.js
- lib/scheduler/scheduler.js
- lib/scheduler/simple-scheduler.js
- lib/scheduler/worker-entry.js
- test/scheduler-registry.js
- test/scheduler.js
- test/simple-scheduler.js
This refactor is intended to simplify the scheduler logic; specifically, to eliminate a gap in resource acquisition tracking when a worker is starting up.
Previously, worker clients like lib/proxy/http.js and lib/proxy/sockjs.js would call getWorker_p, then after the returned promise is successfully resolved with an app worker handle, call acquire() on that handle. The resolution of the promise doesn’t happen until the app has successfully started up (including global.R executing) so it may take a long time. During this window of time, the scheduler has effectively handed out the resource (the worker) but the bookkeeping has not been done yet, since acquire() is not called until later. This gap between resource assignment and bookkeeping is a problem for enforcing resource limits. To …
> Refactor of scheduler

- lib/worker/app-worker.js
This change prevents `createBookmarkStateDirectory_p` from resolving until both the `bookmarkStateDir` and `userBookmarkStateDir` operations are compete.
> Bookmark state dir was resolving too early

- lib/main.js
e.g. `/__assets__/?foo`
This was due to the URL being shortened to `"?foo"` after we get
rid of `/__assets__/`. Changing it to `"/?foo"` fixes it.
> Some asset URL requests were resulting in 500, not 404

- R/SockJSAdapter.R
I recently spent some time chasing a [silly] mis-configuration that
resulted in the R subprocess not starting up.  I wasn't getting any
useful log messages because it was dying before logging had been set up.
This change moves the logging setup code as early as possible in the
setup processes so that errors are logged and usable.
> Set up logging earlier in R subprocess

- NEWS
- lib/router/directory-router.js
Repro case: Navigate to a Shiny app URL but leave off the trailing /.
The piece of code that detects that is supposed to send a redirect
and then `return true;` to indicate that the request was fully handled;
but instead, it sends the redirect and then `return false;`, which
means that it could not be handled and the next handler should take
a crack at it. The final handler in the chain sends a 404 (i.e.
that's the default behavior if no handlers know what to do with it),
but that fails because the redirect was already sent.
> Fix "Can't set headers after they are sent" error in logs

- docker/ubuntu16.04/Dockerfile
This PR adds some packages needed by the Pro build, but should be harmless ™️ to include here too.
I also added a line of `sed` that fixes up `/etc/sudoers` so that hitting enter isn't necessary after `sudo`. This makes life easier for scripts that use `docker exec` to invoke commands involving `sudo`.
> Ubuntu Dockerfile: Added dependencies, eased sudo

- Jenkinsfile
- docker/jenkins/Dockerfile.centos5.9
- docker/jenkins/Dockerfile.centos6.3
- docker/jenkins/Dockerfile.ubuntu-12.04
Implements jenkins pipeline builds for shiny-server.
The pipelines can be found here:
https://buildmaster.rstudioservices.com/job/shiny/job/shiny-server-pipeline/ 
https://buildmaster.rstudioservices.com/job/shiny/job/shiny-server-pro-pipeline/
(there is temporarily no blue ocean link as we have disabled blue ocean due to a few show-stopping bugs).
Notes:
* precise images are a fresh `Dockerfile` with deps needed, centos images are mainly a copy-paste from https://github.com/rstudio/jenkins-docker-images
* Branch builds now persist build files to s3, builds on master persist to the standard location.
* Any branches in GH that have `Jenkinsfile`s in them will automatically be added to the pipeline, and builds will execute on every push.
TODOs:
* `doc`/`deploy` builds, if used. this process …
> Jenkins pipeline builds

- templates/error.html
tempates/directoryIndex.html has been using HTTPS for getting Google Fonts for several years, [see commit](https://github.com/rstudio/shiny-server/commit/f04e462ec5497c070b1301e280a56967af1436bd), however the error page does not. This has caused Firefox (56.0 on Mac OS X) to either not load the fonts or consider my connection to the server to be insecure. This should resolve the issue and the inconsistency.
> Use HTTPS for Google Fonts on error page

- lib/proxy/http.js
- test/http-proxy.js
We used to go through some trouble to have HTTP keepalive between
browsers and Shiny Server, but not keepalive (Connection: close)
between Shiny Server and Shiny (R process). Previously we cared
about this because when we used unix domain sockets to communicate
between Shiny Server and Shiny, connection pooling didn't work
right (at least not in those days, Node v0.8 probably). Now we
don't use unix domain sockets, but we found out during Winston's
httpuv background-thread work that with keepalive enabled, we
weren't properly resetting header information between requests.
This isn't so bad in local cases, but for the SS->Shiny connection
this could be very bad since we could be proxying requests on
behalf of different users over the same connections.
It turns out that we didn't need to do …
> Fix #637 (SSP): Can't remove headers after they are sent

- NEWS
- config/shiny-server-rules.config
- lib/main.js
- lib/router/config-router.js
- npm-shrinkwrap.json
- package.json
Testing notes: Use Chrome network inspector to see if HTTP responses include `Content-Encoding: gzip` headers.
> Support gzip/deflate compression for HTTP responses

- CMakeLists.txt
- packaging/rpm-script/postinst.sh.in
- packaging/rpm-script/posttrans.sh.in
During upgrades, server restarts were happening during a phase of the rpm
lifecycle where files from BOTH old and new versions of the package were
on disk. In some cases we can get the wrong behavior (e.g. npm packages
existing in a nested location in the old version, whereas it moves to the
top level in the new version; we would (and did) pick up the old version
until the server is restarted).
The correct place to restart is during posttrans. CPackRPM doesn't have
a posttrans feature, but we can fake it by tacking %posttrans to the end
of any other script.
> Move server (re)starting logic to posttrans, for correct upgrades

- NEWS
- lib/core/log.js
Log messages have always contained color codes, which make
log files look weird in utilities like less or editors like
vim.
This commit causes coloring only to be used if stdout is
a tty.
> Don't color logs if not at a terminal

- external/node/CMakeLists.txt
- packaging/make-package-jenkins.sh
We were having trouble building Node.js with a modern enough gcc that
it would compile, but binding to an old enough libstdc++ that we
would just work on older platforms.
> Use prebuilt binaries of Node.js

- NEWS
- lib/main.js
The `X-Powered-By` header in responses currently reports `Express`. This change replaces `X-Powered-By` with `Shiny Server`
Example:
```
alandipert@frito~/g/r/shiny-server➜ curl -I http://localhost:3838/001-hello/
HTTP/1.1 200 OK
X-Powered-By: Shiny Server
x-ua-compatible: IE=edge,chrome=1
content-type: text/html; charset=UTF-8
content-length: 2233
connection: close
Vary: Accept-Encoding
Date: Mon, 14 May 2018 19:46:34 GMT
```
> X-Powered-By now reports Shiny Server

- config/shiny-server-rules.config
- lib/core/iputil.js
- lib/router/config-router.js
- test/iputil.js
Node.js doesn't support url.parse on URLs whose hosts are
IPv6 addresses with zone IDs.
Contrast these two results:
```
> require('url').parse("http://[::1]:3838").hostname
'::1'
> 
> require('url').parse("http://[::1%test]:3838").hostname
''
```
Until this is fixed we'll simply reject listening on these
addresses. You can still listen on them using `::`.
If you try to use a listen directive like `listen 3838 ::1%test;` we should throw a config error saying that zone IDs are not supported.
> Actively reject listening on IPv6 addresses with zone IDs

- NEWS
- lib/main.js
Run shiny-server from the command line. Whenever it exits, use `echo $?` immediately to see the exit code. With previous versions, that should always be `0`. With this fix, it should be non-zero for error cases.
Scenarios to try:
1. Hit Ctrl-C to stop the server (equivalent of sending SIGINT)
2. From another terminal, `killall -SIGTERM shiny-server` (might need sudo)
3. Try to start shiny-server with invalid directives in the shiny-server.conf config file
4. `shiny-server --version` (this one _should_ return `0`)
I'm not sure, but I think maybe this will help systemd to more reliably restart on failure (only)? I don't actually know the behavior today--I think it does restart shiny-server automatically, even though the exit code has always been 0.
> Exit code should be nonzero in case of error

- npm-shrinkwrap.json
- package.json
There were some PRs that had not been merged, plus the one that prevents MS Edge from using xhr-streaming.
> Use newer build of shiny-server-client

- config/shiny-server-rules.config
This is in response to issue https://github.com/rstudio/shiny-server/issues/287, and brings this paragraph of the open-source doc to match the Pro doc. 
Companion to pull request https://github.com/rstudio/shiny-server-pro/pull/779 on the SSP portion of the documentation.
> Added note that setting app_idle_timeout to 0 will disable. 

- npm-shrinkwrap.json
- package.json
- packaging/make-package.sh
- tools/check-licenses.js
This shrinks the node_modules directory from ~54MB to ~24MB.
This also fixes the build, as previously, `tools/preflight.sh` was failing due to the `rewire` dependency using an unrecognized license string (`"Apache License, Version 2.0"` instead of the more common `"Apache-2.0"` or `"Apache 2.0"`). Now we accept that license string and also don't include rewire in the binary package.
> Exclude testing-related npm packages from installer

- Jenkinsfile
The tests were failing because the npm modules the tests use weren't available. Doing a regular `npm install` first should solve it, and it shouldn't affect the rpm/deb we build because that should've already happened.
> Install all dependencies before running tests

- npm-shrinkwrap.json
- package.json
@wch pointed me to #412 and I thought to run `npm audit` to get a full dependency vulnerability picture. 
According to `npm audit`, there were 15 vulnerabilities (1 moderate, 15 high) across our 708 dependencies, including `lodash` and `handlebars` (the two mentioned in #412).
The full report is attached: [audit.txt](https://github.com/rstudio/shiny-server/files/3941451/audit.txt)
I applied `npm audit fix` and this PR is the result.
I did some smoke testing (notes below), but if we merge this, I imagine further testing will be desirable.
I can see also omitting upgrades for dependencies that pose no actual risk because of the Shiny Server design, but I haven't taken the time yet to identify those. Please let me know if performing that analysis and coming up with a reduced set of upgrades …
> Update 15 vulnerable packages using `npm audit fix`

- NEWS
- config/shiny-server-rules.config
- lib/router/config-router-util.js
Fixes #418 
Try the new `disable_protocols` values of `streaming` and `polling`. See what effect they have on the available protocols (you can see them by showing the Protocol Selector in a Shiny app).
You can tell which protocols are supposed to be streaming or polling by looking at the table here:
https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https
> Simplify usage of `disable_protocols`

- R/SockJSAdapter.R
- lib/worker/app-worker.js
shiny-server consumes R processes' stdout forever. There's no reason to do this once the information we're looking for has been detected.
> Stop monitoring R stdout after expected data is received

- NEWS
- config/shiny-server-rules.config
- lib/worker/app-worker.js
Add environment variable `SHINY_LOG_STDERR=1` before running shiny-server. You can do this in a couple of ways:
When running from the command line, you can just do `sudo SHINY_LOG_STDERR=1 shiny-server`.
From systemd, edit `/etc/systemd/system/shiny-server.service`, adding the line `Environment=SHINY_LOG_STDERR=1` under the `[Service]` heading. Then run `systemctl daemon-reload`, then `systemctl restart shiny-server`.
> Allow sending of R logs to stderr

- NEWS
- lib/proxy/sockjs.js
This SockJS URL has apparently been broken for some time. We haven't noticed because it's almost never used; in almost every case, we load sockjs.min.js using our own internal copy. It's only the iframe-based protocols (which have been obsolete since IE10) that reference this URL.
In the future we should try to simplify the suite of transports to just websocket, xhr-streaming, xhr-polling, and *maybe* one more. However, we'll need to take existing `disable_protocol` directives into account, and try to figure out what their intent was.
> Remove cloudfront SockJS reference which is broken

- assets/shiny-server.css
The "disconnected from server" grey box doesn't explicitly set a text justification. When a page's body tag has a center align, the message gets center aligned within the box, which looks strange. I think the message should always look the same.
> CSS: align-left to the "disconnected from server" message

- NEWS
- lib/scheduler/scheduler.js
In lib/scheduler/scheduler.js there's a call to posix.getpwnam. If an error is raised there, cleanup is incomplete; in particular, the workerEntry for the new (now failed) worker is not removed. This broken worker is then reused as if it is working, returning the same error to every new client.
This fix simply removes the workerEntry.
(For context: I found this due to an SSP customer having a mysterious `EPIPE` error occur right at this spot in the code. I don't yet know what's causing the `EPIPE`, but this fixes the secondary effect: whatever app triggered the `EPIPE` would constantly return that same error message after that point, until the shiny-server process was restarted.)
I can't think of a way to trigger an error at the exact point where it needs to be triggered for this fix to …
> Fix persistent launch error

- NEWS
- lib/router/directory-router.js
The directory-router has two ways of serving a URL: by proxying to
a Shiny app, or by serving a static file (or directory listing) from
disk. Previously, the URL parsing logic for the two code paths was
totally different, and the former code path was more carefully coded
against possibly malicious or malformed URLs. Unfortunately, URLs
that were rejected by the former code path were then passed on to
the latter code path.
This change ensures that failure to pass URL checks cause the router
to give up on servicing the request (leading to a 404, probably).
> Fix security vulnerability

- NEWS
- lib/router/router.js
A customer reported that a broken `app_dir` (e.g. root directory
that doesn't exist) caused many apps on the server to be broken,
not just the broken app itself. This is because during routing
(i.e. getAppSpec_p()), the locations are tried one after another
to see if they match the request URL. In the case of app_dir,
the SingleAppRouter.getAppSpec_p method was doing a bunch of
directory reading before even looking to see if the URL was
a match; if that directory reading failed, the request would
see a 500 error or whatever.
With this change, an error should only be seen when a broken
app is actually being requested.
Add a section like this to the config file:
```
location /app {
app_dir /blah;
log_dir /var/log/shiny-server;
}
```
This should be done within the `server { }` directive, and …
> SingleAppRouter.getAppSpec_p does too much work before matching URL

- npm-shrinkwrap.json
- package.json
- src/posix.cc
The warnings are the same as this issue: https://github.com/nodejs/nan/issues/807
> Squelch nan-related compiler warning; upgrade shiny-server-client

- npm-shrinkwrap.json
- package.json
See the example in #499. That PR did not fix jsonp-polling, this one does.
The actual code change is in my fork of sockjs-client, [here](https://github.com/jcheng5/sockjs-client/commit/e10d608cc444d554de5b4e861e7c54bfcbb4084f).
> Fix jsonp-polling unresponsiveness (similar to #499)

- packaging/rpm-script/posttrans.sh.in
On a Rocky Linux 8 AMI on EC2, the shiny-server systemd service was not installed, because the `/etc/init` existed, which led the installer to conclude that upstart, not systemd, should be used. This PR reorders the checks so systemd is considered first.
> Change priority of upstart vs. systemd for rpm

- NEWS
- R/SockJSAdapter.R
- lib/core/url-util.js
- lib/router/directory-router.js
- lib/router/router.js
This PR allows Shiny Server to treat .qmd files the same as .Rmd files. The only difference is that .qmd files _only_ work in prerendered mode; we go out of our way to prevent document rendering from occurring in any directory that contains .qmd.
Using this file:
````
---
title: "Old Faithful"
format: html
server: shiny
---
```{r}
sliderInput("bins", "Number of bins:", 
min = 1, max = 50, value = 30)
plotOutput("distPlot")
```
```{r}
#| context: server
output$distPlot <- renderPlot({
x <- faithful[, 2]  # Old Faithful Geyser data
bins <- seq(min(x), max(x), length.out = input$bins + 1)
hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```
````
1. Save the document above on a local machine with Quarto installed, with the filename `index.qmd`.
2. In the directory with …
> Recognize qmd extension as quarto

- NEWS
- lib/transport/tcp.js
Fixes https://github.com/rstudio/shiny/issues/3086 (or at least significantly lifts the ceiling, from 64MB to 512MB). See https://github.com/rstudio/shiny/issues/3086#issuecomment-703802470 for a repro tool.
> Increase server->client message size limit

- NEWS
- R/SockJSAdapter.R
- config/shiny-server-rules.config
- python/SockJSAdapter.py
Fixes #469
Fixes #554
[Universal Analytics is going away](https://support.google.com/analytics/answer/11583528?hl=en&sjid=7400348922365190905-NA) and will stop processing data on July 1, 2023. The analytics code for this style of GA tracking uses IDs that start with `UA-`.
Google Analytics users should [switch to Google Analytics 4](https://support.google.com/analytics/answer/10759417?sjid=7400348922365190905-NA), which requires new tracking code that uses [a Google tag](https://support.google.com/analytics/answer/9744165?sjid=7400348922365190905-NA#install-manually&zippy=%2Cin-this-article%2Cinstall-a-google-tag).
This PR follows the [Install the Google tag (gtag.js)](https://developers.google.com/tag-platform/gtagjs/install) article and updates the GA tracking code to use the JavaScript …
> Use new Google tag-style anayltics code

- lib/router/config-router.js
- npm-shrinkwrap.json
- package.json
For Node.JS since version 12 sort is already stable, meaning anything released after 2019 is fine (compare https://nodejs.org/en/about/previous-releases).
Note that `package.json` still contains "node>=6.6.0" but `.nvmrc` already uses v18.x.
> Remove `stable` package in favor of native stable sort
